# Generated by Django 4.2.7 on 2023-11-13 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 13, 13, 39, 43, 878289, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
