# Generated by Django 3.2.9 on 2023-11-24 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20231113_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 44, 5, 185199, tzinfo=utc)),
        ),
    ]
