# Generated by Django 3.2.9 on 2023-11-29 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 12, 32, 56, 877890, tzinfo=utc)),
        ),
    ]
